/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desain_basdat;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LENOVO
 */
public class AdminHome extends javax.swing.JFrame {

    String filename = null;
    byte[] person_image = null;
    
    int harga_frame = 0;
    int harga_lensa = 0;
    int harga_akhir = 0;
    
    public AdminHome() {
        initComponents();
        show_pemesanan();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    
    public ArrayList<Pemesanan> pemesananList() {
        ArrayList<Pemesanan> pemesananList = new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;" +
                        "databaseName=Kacamata;" +
                        "user=Ridha;" +
                        "password=kelompok7;" +
                        "encrypt=true;" +
                        "trustServerCertificate=true;" + "loginTimeout=30;";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT id, nama_pelanggan, nomor, frame, lensa, total_harga, image, user_sno FROM Pemesanan JOIN [User] ON Pemesanan.user_sno = [User].sno";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Pemesanan pemesanan;
            while(rs.next()){
                pemesanan = new Pemesanan(rs.getInt("id"), rs.getString("nama_pelanggan"), rs.getString("nomor"), rs.getString("frame"), rs.getString("lensa"), rs.getString("total_harga"), rs.getBytes("image"), rs.getInt("user_sno"));
                pemesananList.add(pemesanan);
            }
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
        }
        return pemesananList;
    }
    
    public void show_pemesanan() {
        ArrayList<Pemesanan> list = pemesananList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Pemesanan.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[7];
        for(int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getsno();
            row[1] = list.get(i).getnama_pelanggan();
            row[2] = list.get(i).getnomor();
            row[3] = list.get(i).getframe();
            row[4] = list.get(i).getlensa();
            row[5] = list.get(i).gettotal_harga();
            row[6] = list.get(i).getuser_sno();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lensa = new javax.swing.JComboBox<>();
        frame = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        total_harga = new javax.swing.JLabel();
        hitung_harga = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        lbl_hasil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Pemesanan = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name Pelanggan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nomor Telfon/WA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Frame");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Lensa");

        lensa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Silinder", "Plus", "Minus", "Silinder & Minus", "Silinder & Plus" }));
        lensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lensaActionPerformed(evt);
            }
        });

        frame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Versace", "Dolce", "Levis", "Calvin", "Chanel", "Oakley" }));
        frame.setMinimumSize(new java.awt.Dimension(121, 22));
        frame.setPreferredSize(new java.awt.Dimension(121, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Harga");

        total_harga.setText("0");

        hitung_harga.setText("Hitung Harga");
        hitung_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_hargaActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.setMaximumSize(new java.awt.Dimension(102, 23));
        reset.setMinimumSize(new java.awt.Dimension(102, 23));
        reset.setPreferredSize(new java.awt.Dimension(102, 23));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Admin");

        jTable_Display_Pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Pelanggan", "Nomor", "Frame", "Lensa", "Total Harga", "Username Customer"
            }
        ));
        jTable_Display_Pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_PemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Pemesanan);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        btnImage.setText("Choose");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(lbl_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(550, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(55, 55, 55)
                                            .addComponent(hitung_harga))
                                        .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(lensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hitung_harga))
                                    .addGap(45, 45, 45)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnImage)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitung_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_hargaActionPerformed
        if(frame.getSelectedItem().toString().equals("Kosong")) {
            harga_frame = 0;
        } else if(frame.getSelectedItem().toString().equals("Versace")) {
            harga_frame = 320000;
        } else if(frame.getSelectedItem().toString().equals("Dolce")) {
            harga_frame = 220000;
        } else if(frame.getSelectedItem().toString().equals("Levis")) {
            harga_frame = 400000;
        } else if(frame.getSelectedItem().toString().equals("Calvin")) {
            harga_frame = 350000;
        } else if(frame.getSelectedItem().toString().equals("Chanel")) {
            harga_frame = 190000;
        } else if(frame.getSelectedItem().toString().equals("Oakley")) {
            harga_frame = 150000;
        }
                
                
        if(lensa.getSelectedItem().toString().equals("Kosong")) {
            harga_lensa = 0;
        } else if(frame.getSelectedItem().toString().equals("Silinder")) {
            harga_lensa = 250000;
        } else if(frame.getSelectedItem().toString().equals("Minus")) {
            harga_lensa = 200000;
        } else if(frame.getSelectedItem().toString().equals("Plus")) {
            harga_lensa = 150000;
        } else if(frame.getSelectedItem().toString().equals("Silinder & Minus")) {
            harga_lensa = 400000;
        } else if(frame.getSelectedItem().toString().equals("Silinder & Plus")) {
            harga_lensa = 350000;
        }
        
        
        harga_akhir = harga_frame + harga_lensa;
        String hasil = String.valueOf(harga_akhir);            
        total_harga.setText(hasil);
    }//GEN-LAST:event_hitung_hargaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nama_pelanggan.setText("");
        nomor.setText("");
        frame.setSelectedIndex(0);
        lensa.setSelectedIndex(0);
        total_harga.setText("0");
    }//GEN-LAST:event_resetActionPerformed

    private void jTable_Display_PemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_PemesananMouseClicked
        int i = jTable_Display_Pemesanan.getSelectedRow();
        TableModel model = jTable_Display_Pemesanan.getModel();
        nama_pelanggan.setText(model.getValueAt(i, 1).toString());
        
        nomor.setText(model.getValueAt(i,2).toString());
        
        String frame1 = model.getValueAt(i, 3).toString();
        switch (frame1) {
            case "Kosong":
                frame.setSelectedIndex(0);
                harga_frame = 0;
                break;
            case "Versace":
                frame.setSelectedIndex(1);
                harga_frame = 320000;
                break;
            case "Dolce":
                frame.setSelectedIndex(2);
                harga_frame = 220000;
                break;
            case "Levis":
                frame.setSelectedIndex(3);
                harga_frame = 400000;
                break;
            case "Calvin":
                frame.setSelectedIndex(4);
                harga_frame = 350000;
                break;
            case "Chanel":
                frame.setSelectedIndex(5);
                harga_frame = 190000;
                break;
            case "Oakley":
                frame.setSelectedIndex(6);
                harga_frame = 150000;
                break;
        }
        
        
        
        String lensa1 = model.getValueAt(i, 4).toString();
        switch (lensa1) {
            case "Kosong":
                lensa.setSelectedIndex(0);
                harga_lensa = 0;
                break;
            case "Silinder":
                lensa.setSelectedIndex(1);
                harga_lensa = 250000;
                break;
            case "Minus":
                lensa.setSelectedIndex(2);
                harga_lensa = 200000;
                break;
            case "Plus":
                lensa.setSelectedIndex(3);
                harga_lensa = 150000;
                break;
            case "Silinder & Minus":
                lensa.setSelectedIndex(4);
                harga_lensa = 400000;
                break;
            case "Silinder & Plus":
                lensa.setSelectedIndex(5);
                harga_lensa = 350000;
                break;
        }   
        byte[] img = (pemesananList().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH));
        lbl_image.setIcon(imageIcon);
    }//GEN-LAST:event_jTable_Display_PemesananMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        AdminTambah field = new AdminTambah();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;" +
                        "databaseName=Kacamata;" +
                        "user=Ridha;" +
                        "password=kelompok7;" +
                        "encrypt=true;" +
                        "trustServerCertificate=true;" + "loginTimeout=30;";
            Connection con = DriverManager.getConnection(url);
            int row = jTable_Display_Pemesanan.getSelectedRow();
            String value = (jTable_Display_Pemesanan.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE [Pemesanan] SET nama_pelanggan=?, nomor=?, frame=?, lensa=?, total_harga=? where id=" + value;
            
            PreparedStatement pst = con.prepareStatement(query);
                
            pst.setString(1, nama_pelanggan.getText());
            pst.setString(2, nomor.getText());
            pst.setString(3, frame.getSelectedItem().toString());
            pst.setString(4, lensa.getSelectedItem().toString());
            pst.setString(5, total_harga.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable_Display_Pemesanan.getModel();
            model.setRowCount(0);
            show_pemesanan();

            JOptionPane.showMessageDialog(null, "Update Sucessfully");
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;" +
                        "databaseName=Kacamata;" +
                        "user=Ridha;" +
                        "password=kelompok7;" +
                        "encrypt=true;" +
                        "trustServerCertificate=true;" + "loginTimeout=30;";
            Connection con = DriverManager.getConnection(url);
            int row = jTable_Display_Pemesanan.getSelectedRow();
            String value = (jTable_Display_Pemesanan.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM [Pemesanan] where id="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) jTable_Display_Pemesanan.getModel();
            model.setRowCount(0);
            show_pemesanan();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH));
        lbl_image.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
                
            }
            person_image=bos.toByteArray();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void lensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lensaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> frame;
    private javax.swing.JButton hitung_harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Pemesanan;
    private javax.swing.JLabel lbl_hasil;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JComboBox<String> lensa;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField nomor;
    private javax.swing.JButton reset;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel total_harga;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
