/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desain_basdat;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class AdminTambah extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String filename = null;
    byte[] person_image = null;
    
    String frameImage = null;
    
    
    int harga_frame = 0;
    int harga_lensa = 0;
    int harga_akhir = 0;
    
    
    
    public AdminTambah() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lensa = new javax.swing.JComboBox<>();
        frame = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        total_harga = new javax.swing.JLabel();
        hitung_harga = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        lbl_hasil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lbl_frame_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name Pelanggan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nomor Telfon/WA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Frame");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Lensa");

        lensa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Silinder", "Plus", "Minus", "Silinder & Minus", "Silinder & Plus" }));

        frame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Versace", "Dolce", "Levis", "Calvin", "Chanel", "Oakley" }));
        frame.setMinimumSize(new java.awt.Dimension(121, 22));
        frame.setPreferredSize(new java.awt.Dimension(121, 22));
        frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Harga");

        add.setText("Tambah");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        total_harga.setText("0");

        hitung_harga.setText("Hitung Harga");
        hitung_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_hargaActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.setMaximumSize(new java.awt.Dimension(102, 23));
        reset.setMinimumSize(new java.awt.Dimension(102, 23));
        reset.setPreferredSize(new java.awt.Dimension(102, 23));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Tambah Pesanan");

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnImage.setText("Choose");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        lbl_frame_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hitung_harga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lbl_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 57, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lbl_frame_image, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(78, 78, 78)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung_harga)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImage)
                        .addGap(61, 61, 61)
                        .addComponent(lbl_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_frame_image, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        if(nama_pelanggan.getText().trim().isEmpty() || nomor.getText().trim().isEmpty() || total_harga.getText().equals("0")) {
            lbl_hasil.setText("Isi nama pelanggan dan nomor dengan benar atau Anda belum menghitung harga");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;" +
                "databaseName=Kacamata;" +
                "user=Ridha;" +
                "password=kelompok7;" +
                "encrypt=true;" +
                "trustServerCertificate=true;" + "loginTimeout=30;";
                Connection con = DriverManager.getConnection(url);
                String query = "INSERT INTO Pemesanan (nama_pelanggan, nomor, frame, lensa, total_harga, image, user_sno) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, nama_pelanggan.getText());
                pst.setString(2, nomor.getText());
                pst.setString(3, frame.getSelectedItem().toString());
                pst.setString(4, lensa.getSelectedItem().toString());
                pst.setString(5, total_harga.getText());
                pst.setBytes(6, person_image);
                pst.setInt(7, Login.idUser);
                
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Successfully");
                nama_pelanggan.setText("");
                nomor.setText("");
                frame.setSelectedIndex(0);
                lensa.setSelectedIndex(0);
                total_harga.setText("0");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    }//GEN-LAST:event_addActionPerformed

    private void hitung_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_hargaActionPerformed
        if(frame.getSelectedItem().toString().equals("Kosong")) {
            harga_frame = 0;
        } else if(frame.getSelectedItem().toString().equals("Versace [Rp320000]")) {
            harga_frame = 320000;
        } else if(frame.getSelectedItem().toString().equals("Dolce [Rp220000")) {
            harga_frame = 220000;
        } else if(frame.getSelectedItem().toString().equals("Levis [Rp400000]")) {
            harga_frame = 400000;
        } else if(frame.getSelectedItem().toString().equals("Calvin [Rp350000]")) {
            harga_frame = 350000;
        } else if(frame.getSelectedItem().toString().equals("Chanel [Rp190000]")) {
            harga_frame = 190000;
        } else if(frame.getSelectedItem().toString().equals("Oakley [Rp150000]")) {
            harga_frame = 150000;
        }
                
                
        if(lensa.getSelectedItem().toString().equals("Kosong")) {
            harga_lensa = 0;
        } else if(frame.getSelectedItem().toString().equals("Silinder [Rp250000]")) {
            harga_lensa = 250000;
        } else if(frame.getSelectedItem().toString().equals("Minus [Rp200000]")) {
            harga_lensa = 200000;
        } else if(frame.getSelectedItem().toString().equals("Plus [Rp150000]")) {
            harga_lensa = 150000;
        } else if(frame.getSelectedItem().toString().equals("Silinder & Minus [Rp400000]")) {
            harga_lensa = 400000;
        } else if(frame.getSelectedItem().toString().equals("Silinder & Plus [Rp350000]")) {
            harga_lensa = 350000;
        }
                
        harga_akhir = harga_frame + harga_lensa;
        String hasil = String.valueOf(harga_akhir);            
        total_harga.setText(hasil);
    }//GEN-LAST:event_hitung_hargaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nama_pelanggan.setText("");
        nomor.setText("");
        frame.setSelectedIndex(0);
        lensa.setSelectedIndex(0);
        total_harga.setText("0");
    }//GEN-LAST:event_resetActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        AdminHome field = new AdminHome();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH));
        lbl_image.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);

            }
            person_image=bos.toByteArray();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void loadImage(String imageName) {
        ImageIcon icon = new ImageIcon(imageName);
        lbl_image.setIcon(icon);
    }
    
    private void frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameActionPerformed
        String selectedText = (String) frame.getSelectedItem(); // Menggunakan comboBox bukan frame
        JOptionPane.showMessageDialog(this, "Selected Text: " + selectedText);
        
        if(selectedText.equals("Versace")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Versace.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Dolce")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Dolce.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Levis")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Levis.png"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Calvin")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Calvin.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Chanel")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Chanel.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Oakley")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Oakley.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        
        
        
//        if ("Versace".equals(selectedText)) {
//            loadImage("Versace.jpeg");
//        } else {
//            // Implementasi logika lain jika diperlukan
//        }
    }//GEN-LAST:event_frameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnImage;
    private javax.swing.JComboBox<String> frame;
    private javax.swing.JButton hitung_harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel lbl_frame_image;
    private javax.swing.JLabel lbl_hasil;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JComboBox<String> lensa;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField nomor;
    private javax.swing.JButton reset;
    private javax.swing.JLabel total_harga;
    // End of variables declaration//GEN-END:variables
}
