/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desain_basdat;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Tambah extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String filename = null;
    byte[] person_image = null;
    
    String frameImage = null;
    
    
    int harga_frame = 0;
    int harga_lensa = 0;
    int harga_akhir = 0;
    
    
    
    public Tambah() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lensa = new javax.swing.JComboBox<>();
        frame = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        total_harga = new javax.swing.JLabel();
        hitung_harga = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        lbl_hasil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lbl_frame_image = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 670));
        setMinimumSize(new java.awt.Dimension(800, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name Pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 142, 150, -1));
        getContentPane().add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 142, 342, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nomor Telfon/WA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 182, 150, -1));
        getContentPane().add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 182, 342, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Frame");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 222, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Lensa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 262, 150, -1));

        lensa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Silinder [Rp250000]", "Plus [Rp200000]", "Minus [Rp150000]", "Silinder & Minus [Rp400000]", "Silinder & Plus [Rp350000]" }));
        getContentPane().add(lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 262, 200, -1));

        frame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Versace [Rp320000]", "Dolce [Rp220000]", "Levis [Rp400000]", "Calvin [Rp350000]", "Chanel [Rp190000]", "Oakley [Rp150000]" }));
        frame.setMinimumSize(new java.awt.Dimension(121, 22));
        frame.setPreferredSize(new java.awt.Dimension(121, 22));
        frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameActionPerformed(evt);
            }
        });
        getContentPane().add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 222, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 302, 150, -1));

        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setText("Tambah");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 110, 40));

        total_harga.setText("0");
        getContentPane().add(total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 303, 149, 20));

        hitung_harga.setText("Hitung Harga");
        hitung_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(hitung_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 30));

        reset.setText("Clear");
        reset.setMaximumSize(new java.awt.Dimension(102, 23));
        reset.setMinimumSize(new java.awt.Dimension(102, 23));
        reset.setPreferredSize(new java.awt.Dimension(102, 23));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 110, 30));

        lbl_hasil.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lbl_hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 501, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Tambah Pesanan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 36, -1, -1));

        kembali.setBackground(new java.awt.Color(255, 102, 102));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 130, 30));

        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 260, 100));

        btnImage.setText("Bukti Pembayaran");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 160, 40));

        lbl_frame_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_frame_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 310, 140));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("BCA 00009998888777");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\backgroundhijau4.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabel7.setMinimumSize(new java.awt.Dimension(800, 500));
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        if(nama_pelanggan.getText().trim().isEmpty() && nomor.getText().trim().isEmpty() && total_harga.getText().equals("0") && lbl_image.getIcon() == null) {
            lbl_hasil.setText("Isi nama pelanggan dan nomor dengan benar atau Anda belum menghitung harga atau belum ada bukti pembayaran");            
            return;
            
        } else if(total_harga.getText().equals("0")) {
            lbl_hasil.setText("Anda Belum Menghitung Harga");
            return;
            
        } else if(lbl_image.getIcon() == null) {
            lbl_hasil.setText("Belum Ada Bukti Pembayaran");
            return;
            
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;" +
                "databaseName=Kacamata;" +
                "user=Ridha;" +
                "password=kelompok7;" +
                "encrypt=true;" +
                "trustServerCertificate=true;" + "loginTimeout=30;";
                Connection con = DriverManager.getConnection(url);
                String query = "INSERT INTO Pemesanan (nama_pelanggan, nomor, frame, lensa, total_harga, image, user_sno) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, nama_pelanggan.getText());
                pst.setString(2, nomor.getText());
                pst.setString(3, frame.getSelectedItem().toString());
                pst.setString(4, lensa.getSelectedItem().toString());
                pst.setString(5, total_harga.getText());
                pst.setBytes(6, person_image);
                pst.setInt(7, Login.idUser);
                
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Successfully");
                nama_pelanggan.setText("");
                nomor.setText("");
                frame.setSelectedIndex(0);
                lensa.setSelectedIndex(0);
                total_harga.setText("0");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    }//GEN-LAST:event_addActionPerformed

    private void hitung_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_hargaActionPerformed
        if(frame.getSelectedItem().toString().equals("Kosong")) {
            harga_frame = 0;
        } else if(frame.getSelectedItem().toString().equals("Versace [Rp320000]")) {
            harga_frame = 320000;
        } else if(frame.getSelectedItem().toString().equals("Dolce [Rp220000")) {
            harga_frame = 220000;
        } else if(frame.getSelectedItem().toString().equals("Levis [Rp400000]")) {
            harga_frame = 400000;
        } else if(frame.getSelectedItem().toString().equals("Calvin [Rp350000]")) {
            harga_frame = 350000;
        } else if(frame.getSelectedItem().toString().equals("Chanel [Rp190000]")) {
            harga_frame = 190000;
        } else if(frame.getSelectedItem().toString().equals("Oakley [Rp150000]")) {
            harga_frame = 150000;
        }
                
                
        if(lensa.getSelectedItem().toString().equals("Kosong")) {
            harga_lensa = 0;
        } else if(lensa.getSelectedItem().toString().equals("Silinder [Rp250000]")) {
            harga_lensa = 250000;
        } else if(lensa.getSelectedItem().toString().equals("Minus [Rp150000]")) {
            harga_lensa = 150000;
        } else if(lensa.getSelectedItem().toString().equals("Plus [Rp200000]")) {
            harga_lensa = 200000;
        } else if(lensa.getSelectedItem().toString().equals("Silinder & Minus [Rp400000]")) {
            harga_lensa = 400000;
        } else if(lensa.getSelectedItem().toString().equals("Silinder & Plus [Rp350000]")) {
            harga_lensa = 350000;
        }
                
        harga_akhir = (harga_frame + harga_lensa);
        String hasil = String.valueOf(harga_akhir);            
        total_harga.setText(hasil);
    }//GEN-LAST:event_hitung_hargaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nama_pelanggan.setText("");
        nomor.setText("");
        frame.setSelectedIndex(0);
        lensa.setSelectedIndex(0);
        lbl_frame_image.setIcon(null);
        lbl_image.setIcon(null);
        total_harga.setText("0");
    }//GEN-LAST:event_resetActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Home field = new Home();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH));
        lbl_image.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);

            }
            person_image=bos.toByteArray();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void loadImage(String imageName) {
        ImageIcon icon = new ImageIcon(imageName);
        lbl_image.setIcon(icon);
    }
    
    private void frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameActionPerformed
        String selectedText = (String) frame.getSelectedItem(); // Menggunakan comboBox bukan frame
        JOptionPane.showMessageDialog(this, "Selected Text: " + selectedText);
        
        if(selectedText.equals("Versace [Rp320000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Versace.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
                
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Dolce [Rp220000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Dolce.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Levis [Rp400000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Levis.png"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Calvin [Rp350000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Calvin.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Chanel [Rp190000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Chanel.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if(selectedText.equals("Oakley [Rp150000]")) {
            String pathGambar = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\Desain_Basdat\\src\\main\\java\\com\\mycompany\\desain_basdat\\Oakley.jpeg"; // Ganti dengan path gambar yang sesuai

            // Coba baca gambar dari file dan atur sebagai ikon pada JLabel
            try {
                File fileGambar = new File(pathGambar);
                Image gambar = ImageIO.read(fileGambar);
                lbl_frame_image.setIcon(new ImageIcon(gambar));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        
        
        
//        if ("Versace".equals(selectedText)) {
//            loadImage("Versace.jpeg");
//        } else {
//            // Implementasi logika lain jika diperlukan
//        }
    }//GEN-LAST:event_frameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnImage;
    private javax.swing.JComboBox<String> frame;
    private javax.swing.JButton hitung_harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel lbl_frame_image;
    private javax.swing.JLabel lbl_hasil;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JComboBox<String> lensa;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTextField nomor;
    private javax.swing.JButton reset;
    private javax.swing.JLabel total_harga;
    // End of variables declaration//GEN-END:variables
}
